### ISSUE TITLE
Reusable Blocks are not available

### ISSUE THREAD

**Issue by jaakjuu1** [digitoimistodude/air-light#116]
In functions.php on line 159 `'core/reusableBlock',` should enable reusable blocks for all post types. This does not work. 

I replaced this line with `'core/block',` and the reusable blocks appeared. I don't know if it's the correct fix but worked.

**Comment by michaelbourne** [comment]
This is the correct fix, fyi.

**Comment by ronilaukkarinen** [comment]
Fixed in [7.9.5](https://github.com/digitoimistodude/air-light/releases/tag/7.9.5).
