### ISSUE TITLE
Support this theme React development?

### ISSUE THREAD

**Issue by aaron5670** [digitoimistodude/air-light#120]
Support this theme React development?
Can I find a example somewhere?

**Comment by ronilaukkarinen** [comment]
This theme supports modern JavaScript, yes. You just need to implement React to your gulp build process. We have currently no ready-made examples of any react projects as the general purpose of this theme is to use JavaScript as part of the websites. If you are looking for a SPA build it may get a bit trickier to get it to work but it's certainly possible. If you decide to go for it, let us know how it went!
