### ISSUE TITLE
phpcs.xml Error.

### ISSUE THREAD

**Issue by SteveJonesDev** [digitoimistodude/air-light#126]
I'm getting the error below when editing PHP. I didn't see a phpcs.xml file in the theme directory. Does this need to be install via composer or something? Thanks for your help?

![Screen Shot 2021-10-06 at 12 26 30 PM](https://user-images.githubusercontent.com/2895788/136244880-9271b226-07db-467e-bd49-04fd12a31f06.png)

**Comment by ronilaukkarinen** [comment]
Can you give me a little bit more information:

- What OS are you running it on? For Windows things are a bit different
- What kind of stack are you using air-light with? Is your setup based on our tools or something completely different?
- Have you installed a dev version of the theme via script or manually or from WordPress Theme Directory?
- Have you followed the instructions on Wiki?

**Comment by SteveJonesDev** [comment]
The only difference is that I don't have WP core included in my project folder. I just created a symbolic link from the theme directory to my Local by Flywheel install's themes folder.

**Comment by ronilaukkarinen** [comment]
It's hard to say without knowing your setup exactly. I have no experience in Local by Flywheel but I'm trying to help.

The fact your are missing phpcs.xml either sounds like you missed the part in [development steps](https://github.com/digitoimistodude/air-light/wiki/Using-with-Local-by-Flywheel-or-other-3rd-party-development-environment#development-steps-and-custom-post-types-cpts) where you should copy [our devtools](https://github.com/digitoimistodude/devpackages) or install [debuggers](https://github.com/digitoimistodude/air-light#debuggers) or your [themeDir](https://github.com/digitoimistodude/devpackages/blob/eabe6ef351a794922c495a0dd35cc5bc2fc589f5/gulp/config.js#L1) just points out to wrong directory (I wonder where did that "resourcessharingproject/phpcs.xml" path came from?)

Are you running gulp from project root or from theme folder? Our setup relies that you run your own dev tools in project base and setup them correctly OR you use our devpackages (as explained in wiki and in this comment).

Theme base gulp is meant strictly to [air-light development](), I mean [developing the starter theme itself](https://github.com/digitoimistodude/air-light#air-development) and NOT the theme created based on the starter theme.

**Comment by ronilaukkarinen** [comment]
> Hey @ronilaukkarinen I also face the same issue with the Wordpress Theme version of Air-light theme. I am too using Local by flywheel because it very very intuitive and easy way of setting up LEMP stack on a Windows machine.

I do know the advantages of Local for its easiness. If you are anything of a tinkering sort, there is a [proven way for Windows 10](https://rolle.design/local-server-on-windows-10-for-wordpress-theme-development) to use our stack and Air-light, if you might not know about it. However, it's not recommended if you are not comfortable with setting up servers or living in the command line interface.

> After activating the theme, I too find similar problem of Gutenberg blocks not working as shown in the screenshot by @SteveJonesDev

Have you tried running `gulp js` or saving _js/src/front-end.js_ while `gulp` watch process is running? What kind of errors are outputted in console?

> Please do let me know how to solve it and also, please tell me how to proceed further with development of an AdobeXD or Figma or Sketch design into fully functional WP theme based on Air-light ?

I'm not sure what you mean exactly. Care to elaborate?

**Comment by xyeres** [comment]
Not to be “that guy” digging up an old issue but today I noticed the missing phpcs.xml in the current setup docs for third party stacks. There was no mention of it being necessary until I had an error from phpcs. I figured out that I needed to copy phpcs.xml over to my  project to get it setup. Something to add to the instructions I think!

**Comment by ronilaukkarinen** [comment]
Third party stacks are always a bit unsure ground for us, because our full focus is [dudestack](https://github.com/digitoimistodude/dudestack) and the [LEMP of our own](https://github.com/digitoimistodude/macos-lemp-setup).

Added to [Wiki](https://github.com/digitoimistodude/air-light/wiki/Using-with-Local-by-Flywheel-or-other-3rd-party-development-environment).

**Comment by ronilaukkarinen** [comment]
> Thanks for lending supporting to us third-party folks :) I'm working for a small agency and we've used air-light for several recent projects, we are now working to integrate it as the base for our new workflow. I hope to contribute back to air-light as I understand it more

Glad you like and use the theme! 👍
