### ISSUE TITLE
gulp-uglify-es to support ES6 support question. 

### ISSUE THREAD

**Issue by rgfx** [digitoimistodude/air-light#13]
Isn't it dangerous to use ES6 without a transpiler (browser support), wouldn't it better just to use babel then uglify instead? Maybe am not getting something, curious. Thanks

**Comment by timiwahalahti** [comment]
You are right, using babel would better and more robust in name of browser support. I'm happy to merge PR ;)

**Comment by ronilaukkarinen** [comment]
Finally solved in 6.0.4 where we had utter and complete js build process rewrite so closing this issue.
