### ISSUE TITLE
Tailwind integration to theme

### ISSUE THREAD

**Issue by iniznet** [digitoimistodude/air-light#130]
I have been enjoying using this starter theme so far, popped in mind that now tailwind has JIT mode which is really helpful in the development process as it doesn't have blob size at the start and only keeps CSS that being used in production, but I'm having trouble integrating the tailwind with the current gulp+webpack environment, any advice for this issue?

Right now, I'm thinking to have tailwind separated from gulp.

**Comment by ronilaukkarinen** [comment]
Glad you are enjoying Air-light! We try to avoid all CSS framework so Tailwind is not something we are going to officially support.

You could do as we do with other CSS/JS packs:

In theme: `npm i tailwindcss --save`, then just `@import 'tailwindcss/tailwind;` to global.scss. At least that's how I think it's supposed to work. Of course it will include all tailwind CSS, not just the ones being in use. Or, you could just import the ones you use and go with that? No JS needed.

As for the JIT, can you link to the example? Never really used Tailwind myself as I strongly dislike defining style related things in HTML with numbers.

With JS the normal process is similar. You just npm install and then import the required to front-end.js like this:

https://github.com/digitoimistodude/air-light/blob/11a4f49ca9f4bb9b5325ceb1c795bed42cadf678/js/src/front-end.js#L6

I hope this helps.

**Comment by iniznet** [comment]
As for the example, I think [logrocket](https://blog.logrocket.com/exploring-jit-mode-tailwind-css/) might cover it

My main goal using JIT is only for generating styles on-demand feature with watch mode instead of generating everything in advance at initial build time.

In every theme, I have it separated from webpack/gulp environment due to it disabling the @apply directive which make me unable to create my own CSS, so I run the tailwind + watch mode with a separated terminal from gulp/webpack.

**Comment by ronilaukkarinen** [comment]
I'm not sure how it should work but as tailwind configs are in js similar to webpack's it should work bundled in theory. But as I said I have no experience in Tailwind and not much interest to fiddle with it. I have tried tailwind just now with its own unpublished branch and got a bit frustrated with it precisely because `@apply` and other tailwind-related things wouldn't just work with webpack + postscss-sass out of the box.

Again, just speculating, but couldn't you just add tailwind support in your webpack config? Like `require('@tailwindcss/jit')` or I think it's `require('tailwindcss')` [nowadays](https://github.com/tailwindlabs/tailwindcss/issues/4000).

Air-light is awaiting an update from webpack4 to webpack5 (it's in testing phase) but I'm not sure whether it's going to help integrating with Tailwind.

I hope you get it right. Let me know how it goes, maybe we could add Tailwind + JIT support to the [Wiki](https://github.com/digitoimistodude/air-light/wiki) after you get it working properly.

**Comment by iniznet** [comment]
I'm able to integrate the tailwind into gulp, though it was not perfect setup, but at least it's possible to use tailwind with its directives in the sass file, I modified devstyles, prodstyles, and watch gulp tasks into these

devstyles.js
```
...
const tailwindcss = require('tailwindcss');
....
function devstyles() {
  return src(config.styles.src)

    // Try to inject CSS first
    .pipe(bs.stream())

    // Init source maps
    .pipe(sourcemaps.init())

    // Compile SCSS asynchronously
    .pipe(sass.sync(config.styles.opts.development))

    // Save compiled for tailwind process *needed*
    .pipe(dest(config.styles.development))

    // Run PostCSS plugins
    .pipe(postcss([tailwindcss, autoprefixer()]))

    // Write source maps
    .pipe(sourcemaps.write())

    // Save expanded version for development and for BS to inject
    .pipe(dest(config.styles.development))
}
```
prodstyles.js
```
...
const tailwindcss = require('tailwindcss');
....
function prodstyles() {
  return src(config.styles.src)

    // Compile first time to CSS to be able to parse CSS files
    .pipe(sass(config.styles.opts.development))

    // Save compiled for tailwind process *needed*
    .pipe(dest(config.styles.production))

    // Run PostCSS plugins
    .pipe(postcss([tailwindcss, autoprefixer()]))

    // Production settings
    .pipe(sass.sync(config.styles.opts.production))

    // Compress and minify CSS files
    .pipe(cleancss(config.cleancss.opts,
      function (details) {
        console.log('[clean-css] Original: ' + details.stats.originalSize / 1000 + ' kB');
        console.log('[clean-css] Minified: ' + details.stats.minifiedSize / 1000 + ' kB');
        console.log('[clean-css] Compression time: ' + details.stats.timeSpent + ' ms');
        console.log('[clean-css] Compression rate: ' + details.stats.efficiency * 100 + ' %');
      }), )

    // Save the final version for production
    .pipe(dest(config.styles.production));
}
```

watch.js
```
// Task
function watchfiles() {
  bs.init(config.browsersync.src, config.browsersync.opts);
  watch(['./tailwind.config.js', `${config.styles.watch.development}`], series('devstyles', 'lintstyles')).on('error', handleError());
  watch(['./tailwind.config.js', `${config.styles.watch.production}`], series('prodstyles')).on('error', handleError());
  watch(config.php.watch, series('devstyles', 'prodstyles', 'phpcs')).on('change', bs.reload);
  watch(config.js.watch).on('change', series('js'), bs.reload);
};
```

I put tailwind directives from their docs in global.scss as test
```
@charset 'utf-8';
@tailwind base;
@tailwind components;
@tailwind utilities;

.btn {
  @apply font-bold py-2 px-4 rounded;
}

.btn-blue {
  @apply bg-blue-500 hover:bg-blue-700 text-white;
}

@layer base {
  h1 {
    @apply text-2xl;
  }

  h2 {
    @apply text-xl;
  }
}

@layer components {
  .btn-blue {
    @apply bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded;
  }
}

@layer utilities {
  .filter-none {
    filter: none;
  }

  .filter-grayscale {
    filter: grayscale(100%);
  }
}

@responsive {
  .bg-gradient-brand {
    background-image: linear-gradient(blue, green);
  }
}

@screen sm {
  .btn-yellow {
    @apply bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded;
  }
}

...
```

I also added `bg-black` class to `<main>` in index.php and here's the global.css result:
Full result: [global.css Gist](https://gist.github.com/iniznet/faadb2f51654581510f915ea27748150)
```
...
Tailwind base CSS
...
.bg-black {
	--tw-bg-opacity: 1;
	background-color: rgba(0, 0, 0, var(--tw-bg-opacity));
}
.filter {
	filter: var(--tw-filter);
}
.transition {
	transition-property: background-color, border-color, color, fill, stroke, opacity, box-shadow, transform, filter, -webkit-backdrop-filter;
	transition-property: background-color, border-color, color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter;
	transition-property: background-color, border-color, color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter, -webkit-backdrop-filter;
	transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
	transition-duration: 150ms;
}
.btn {
	border-radius: 0.25rem;
	padding-top: 0.5rem;
	padding-bottom: 0.5rem;
	padding-left: 1rem;
	padding-right: 1rem;
	font-weight: 700;
}

.btn-blue {
	--tw-bg-opacity: 1;
	background-color: rgba(59, 130, 246, var(--tw-bg-opacity));
	--tw-text-opacity: 1;
	color: rgba(255, 255, 255, var(--tw-text-opacity));
}

.btn-blue:hover {
	--tw-bg-opacity: 1;
	background-color: rgba(29, 78, 216, var(--tw-bg-opacity));
}
@media (min-width: 640px) {
  .btn-yellow {
		border-radius: 0.25rem;
	}
  .btn-yellow {
		--tw-bg-opacity: 1;
		background-color: rgba(245, 158, 11, var(--tw-bg-opacity));
	}
  .btn-yellow {
		padding-top: 0.5rem;
		padding-bottom: 0.5rem;
	}
  .btn-yellow {
		padding-left: 1rem;
		padding-right: 1rem;
	}
  .btn-yellow {
		font-weight: 700;
	}
  .btn-yellow {
		--tw-text-opacity: 1;
		color: rgba(255, 255, 255, var(--tw-text-opacity));
	}
  .btn-yellow:hover {
		--tw-bg-opacity: 1;
		background-color: rgba(180, 83, 9, var(--tw-bg-opacity));
	}
}
...
```

There's an issue with my modified gulp task where prodstyles task is fired twice when I update SCSS development files, stylelint also gives unknown rules to tailwind directives which I think can be fixed by ignoring them.

It would be great if air-light can (optionally) support tailwind + JIT as it generates style classes that only we use which minimizes the CSS output size and starts growing as we write more classes.

**Comment by ronilaukkarinen** [comment]
Nice! An idea for further thought: We could add a separate tailwind tasks, for example `tailwindprodstyles` and `tailwinddevstyles` and then one could just switch them to the watch.js in place of the original ones. Supporting Tailwind on Wiki level is possible but I'd rather not add it to the official build when it's something everyone is not using. The same goes for React, Vue.js, etc., we are adding them per-project but not in the build because they are not used in every single project.

I'm going to test this is some point and give it more thought. Thanks for everything so far, this is a good start.

**Comment by ronilaukkarinen** [comment]
Currently no time to allocate to this and interest in Tailwind isn't huge in our company. I'm going to close this but if the need rises will reopen it in the future. Thanks for all the ideas!
