### ISSUE TITLE
Can't create project

### ISSUE THREAD

**Issue by malatini42** [digitoimistodude/air-light#132]
Hello, sorry if my comment is bad, I am new to this. I tried to follow your readme but the airdev project won't be created. I am prompted that it was succesfully done but I can't access the front-end or WP-admin and I do not have the folder in my file system (/var/www/airdev). Could you please help me ?

**Comment by ronilaukkarinen** [comment]
No comments are bad in itself :)

Airdev project is only meant for developing Air-light itself, the starter theme. So I have to assume you [followed these instructions](https://github.com/digitoimistodude/air-light#air-development) and want to contribute in developing Air-light?

If you just want to create your _own_ theme based on Air-light, you need to follow [installation instructions on Wiki](https://github.com/digitoimistodude/air-light/wiki).

Your problem sounds more of a web environment / development environment thing and not Air-light issue per se. First of all, are you using what OS? Windows, macOS, Linux? We recommend using Mac + [macos-lemp-setup](https://github.com/digitoimistodude/macos-lemp-setup) as stated in our docs.

We are not exactly a web development support channel so unfortunately we need to keep the issues strictly Air-light based. So I'm going to close this one for now. But please let me know more of what you are trying to do so I do my best to help out.
