### ISSUE TITLE
Lazy loading attribute

### ISSUE THREAD

**Issue by iniznet** [digitoimistodude/air-light#133]
Considering add lazy loading attribute to img tag for browser who support it, otherwise load the lazyload js.
Something like:
```
if ( // check if browser support lazy loading attribute ) {
} else {
  // browser doesn't support it, so load the lazyload js
} 
```
As it explained here: [lazy loading article](https://addyosmani.com/blog/lazy-loading/)
Although current caniuse still around 70%: [caniuse](https://caniuse.com/loading-lazy-attr)

I think it would be great if it was implemented by default without needing to edit the JS every time we set up the starter theme.

**Comment by ronilaukkarinen** [comment]
This is on our roadmap and actually more like [air-helper](https://github.com/digitoimistodude/air-helper#image-lazyloading) related issue.

I have moved your issue [here](https://github.com/digitoimistodude/air-helper/issues/49).
