### ISSUE TITLE
Update readme.md to reflect changes in watch.js

### ISSUE THREAD

**Issue by flegfleg** [digitoimistodude/air-light#135]
There is outdated information under **Debuggers/For gulp**, this is how i disabled PHPCS: 

If you don't want to use phpcs with gulp, you can disable it by changing the line `watch(config.php.watch, series('phpcs')).on('change', bs.reload);` to `watch(config.php.watch).on('change', bs.reload);` in /gulp/tasks/watch.js.

**Comment by ronilaukkarinen** [comment]
Yeah, it can get outdated sometimes as we're fast with updates. While you're at it, please send a PR? Closing this as an issue for now.
