### ISSUE TITLE
Question about phpcs and about size of generated css file

### ISSUE THREAD

**Issue by filipchrapek** [digitoimistodude/air-light#136]
I have one issue and one general question:

1. I'm trying to run your theme with all the default configs and standards, so I added the WP phpcs standard. I confirmed that it has been added globally and within my editor. But when I save any php file I'm getting:

`stdout: ERROR: Referenced sniff "PHPCSUtils" does not exist`

Could you please help me with that?

2. CSS file for production has 124KB. Is that correct?

I'm on Mac OS and I'm using Local.

**Comment by ronilaukkarinen** [comment]
That's weird. No such sniff should be used. You should not use gulp or phpcs.xml from the theme, those are for air-light development only. We actually don't provide a wide-scale support for Local or other environments than [dudestack](https://github.com/digitoimistodude/air-light/wiki/Using-with-Local-by-Flywheel-or-other-3rd-party-development-environment)/[macos-lemp](https://github.com/digitoimistodude/macos-lemp-setup) but I can try to help. For this I'd need a little bit more information on

1. How do you use Air-light, what steps did you take to create your new theme
2. What kind of local environment / stack do you have besides to Local by Flywheel? How WordPress is installed?
3. What editor do you use, VSCode I presume? What is the version of your phpcs installed in editor and system?

CSS for production might have grown over time especially for un-gzipped files. Checked it just now, with `gulp prodstyles` and `wc -c css/prod/global.css` (uncompressed) I get 124,431 kB (from bytes to kB) so you are right about that. We should update the uncompressed amount to README.md. `gzip -c css/prod/global.css | wc -c` (compressed with gzip) I get 16,868 kB (from bytes to kB). You should always use gzip + ngx-pagespeed + and things like RapidLoad in production environments to get the smallest result.

**Comment by filipchrapek** [comment]
Hi Roni!

Before I waste your time, I'll make sure I tried everything.
And regarding the CSS file size - of course, I totally understand that. Just wanted to make sure if that isn't something only from my end.

Actually, I'm coming back to your theme after some time. Glad to see you're still developing it, I think it's really awesome what you are doing. I have couple ideas/remarks/questions about the theme and I'm not sure if I should contact you here tackling each topic individually or maybe there is other way allowing more 'loose' form of feedback.
Please let me know :)

**Comment by ronilaukkarinen** [comment]
@filipchrapek Thanks for the feedback and welcome back! Personally Air-light is my life's work and as long as there's websites to be done I will never stop working on it. It's also one of the key pieces in our web development team. 👍

If you have feature requests or other ideas, just open a new issue for it and we'll tag it as idea or enhancement etc. However please note if it's a matter of functionality, most of those belong to [air-helper](https://github.com/digitoimistodude/air-helper).

**Comment by ronilaukkarinen** [comment]
File sizes have been updated. Closing this ticket for inactivity.
