### ISSUE TITLE
Blog catageories do not appear

### ISSUE THREAD

**Issue by grandeljay** [digitoimistodude/air-light#138]
Hello,

I recently started using this theme and now I noticed that blog categories do not seem to appear. The page works, but there are no posts in it. Weirdly, the pagination does appear.

![image](https://user-images.githubusercontent.com/45571053/148749482-91dacc22-592e-4b67-95ed-33425cc53747.png)

The blog page in general does however seem to work.

- https://domain.tld/category/news/ does **not** work
- https://domain.tld/blog/ **does** work

Am I missing something? Do I need to create a template file? There are no PHP errors.

**Comment by timiwahalahti** [comment]
Hi @grandeljay, thanks for reporting this!

Found the issue right away and will fix it asap. In the meantime, you can fix it by yourself by creating `template-parts/content` file that contains the things you want to show in archives for each post. Or replace the loop in `archive.php` with the same loop that is used for the blog page https://github.com/digitoimistodude/air-light/blob/master/index.php#L34-L46

**Comment by grandeljay** [comment]
That fixed it, thanks!

**Comment by timiwahalahti** [comment]
Fixed in d317b49fb175a80ad8b6001e7ae3fd97b1ae7905. Once again, thank you @grandeljay for noticing this!
