### ISSUE TITLE
Unable to pull from master on Windows

### ISSUE THREAD

**Issue by dylanelliott27** [digitoimistodude/air-light#140]
Hi, I was just about to submit a pull request for the deprecated filter issue, but seem to be getting this error whenever pulling from master: **error: invalid path 'svg/Icon?'**

From my research, it seems that this Icon? file which is in the SVG folder is something for MacOS folder images? However, it seems that it is a restricted name on windows: https://stackoverflow.com/a/44864367

Is this file needed?

**Comment by timiwahalahti** [comment]
Hi @dylanelliott27!

The Icon file is now deleted, it's some MacOS internal junk that shouldn't be in the repo as you said. Sorry for the confusion!
