### ISSUE TITLE
Long JS compilation

### ISSUE THREAD

**Issue by filipchrapek** [digitoimistodude/air-light#143]
What is great about your theme, that it’s almost 'plug & play' experience (with some tweaks obviously). It’s really helpful for folks who want to jump straight into coding and doesn’t really want to spend ages on setting up the automation tools. 

Having said that, I’m wondering if the JS compilation could be faster? Right now if I save the `front-end.js` file, it seems like the JS is being compiled multiple times.
Moreover the browser is being refreshed before the final compilation, so I have to always refresh it manually at the end.

Is it how it suppose to be or I messed something up?

**Comment by ronilaukkarinen** [comment]
Thanks for the compliment. We try to get this as easy start point as possible while providing a decent amount of UI elements and gulp tasks for modern JS/CSS.

Last I tried, the js compile time is pretty fast, should not take more than a second:

![Screen-Shot-2022-01-25-11-24-54 62](https://user-images.githubusercontent.com/1534150/150949158-0f7c727c-eb46-40c3-a0d4-d67b1f5fd7f9.png)

For me also with watch task the window reloads once _after_ the js has been compiled, browsersync takes care of that. It would help a bit if you'd share how exactly did you set up your environment, which Air-light version you are using and do you use our [dudestack](https://github.com/digitoimistodude/dudestack) and/or [devpackages](https://github.com/digitoimistodude/devpackages) or just air clone.

I can't really reproduce this but while stating _it should work_ I know that in larger products tasks can take a bit longer.

Didn't notice anything strange in our setup so right now I'm closing this. Feel free to open the issue again with more details if you did not solve it yet.
