### ISSUE TITLE
White screen when editing page after the WordPress 5.9 update.

### ISSUE THREAD

**Issue by villekujansuu** [digitoimistodude/air-light#144]
I updated my project to the newest WordPress and now when I try to edit a page or post I only get blank white screen. 

Love all your work btw.

**Comment by mlichwa** [comment]
Got the same error. Here is my log:
`[26-Jan-2022 10:09:46 UTC] PHP   1. {main}() ../wp-admin/post.php:0
[26-Jan-2022 10:09:46 UTC] PHP   2. require() ../wp-admin/post.php:187
[26-Jan-2022 10:09:46 UTC] PHP   3. get_block_editor_settings() ../wp-admin/edit-form-blocks.php:278
[26-Jan-2022 10:09:46 UTC] PHP   4. apply_filters_deprecated() ../wp-includes/block-editor.php:416
[26-Jan-2022 10:09:46 UTC] PHP   5. _deprecated_hook() ../wp-includes/plugin.php:662
[26-Jan-2022 10:09:46 UTC] PHP   6. trigger_error() ../wp-includes/functions.php:5691`

In my case, it did help to disable `remove_gutenberg_inline_styles` in hooks.php

**Comment by ronilaukkarinen** [comment]
May I see the full error message some how, seems to be concatted?

https://github.com/digitoimistodude/air-light/blob/03426ce0408286ec94c7ef23e284ef61b798065d/inc/hooks/gutenberg.php#L85-L91

This hook is originally from [here](https://github.com/WordPress/gutenberg/issues/18595#issuecomment-599588153). Something seems to have changed.

We'll check things up in some point regarding to this. In our newest version it's not causing any problems though so something must be different in your setup.

**Comment by mlichwa** [comment]
I've updated my error.log comment. I hope it helps and thank you for looking into it.

**Comment by owsw** [comment]
I think this is related to https://github.com/digitoimistodude/air-light/pull/141 as I had the same issues that were resolved by this merge

**Comment by ronilaukkarinen** [comment]
@owsw Oh, right. Thanks! We'll check it out with @timiwahalahti soon enough!

**Comment by villekujansuu** [comment]
> I think this is related to #141 as I had the same issues that were resolved by this merge

Unfortunately this didn't help. It got rid of those deprecated errors though. 

Don't know if this helps or not, but browsers DevTools gives me these errors:
`JQMIGRATE: Migrate is installed, version 3.3.2

react-dom.min.js?ver=17.0.1:141 

TypeError: l.styles.forEach is not a function
    at edit-post.min.js?ver=aec3905d54d344b48f452da0da95d621:7:93641
    at Object.useMemo (react-dom.min.js?ver=17.0.1:220:462)
    at c.useMemo (react.min.js?ver=17.0.1:30:236)
    at zt (edit-post.min.js?ver=aec3905d54d344b48f452da0da95d621:7:93610)
    at Le (react-dom.min.js?ver=17.0.1:100:3)
    at Pj (react-dom.min.js?ver=17.0.1:231:183)
    at di (react-dom.min.js?ver=17.0.1:168:305)
    at Nj (react-dom.min.js?ver=17.0.1:168:236)
    at sc (react-dom.min.js?ver=17.0.1:168:96)
    at gf (react-dom.min.js?ver=17.0.1:162:109)

Ye @ react-dom.min.js?ver=17.0.1:141

Mh.c.callback @ react-dom.min.js?ver=17.0.1:141
dh @ react-dom.min.js?ver=17.0.1:80
Bj @ react-dom.min.js?ver=17.0.1:145
Qj @ react-dom.min.js?ver=17.0.1:176
unstable_runWithPriority @ react.min.js?ver=17.0.1:24
Za @ react-dom.min.js?ver=17.0.1:73
eb @ react-dom.min.js?ver=17.0.1:170
gf @ react-dom.min.js?ver=17.0.1:162
Pa @ react-dom.min.js?ver=17.0.1:157
yd @ react-dom.min.js?ver=17.0.1:188
(anonymous) @ react-dom.min.js?ver=17.0.1:191
bi @ react-dom.min.js?ver=17.0.1:163
zd @ react-dom.min.js?ver=17.0.1:191
M.render @ react-dom.min.js?ver=17.0.1:243
Qt @ edit-post.min.js?ver=aec3905d54d344b48f452da0da95d621:7
(anonymous) @ post.php?post=2&action=edit:383

react-dom.min.js?ver=17.0.1:177 

Uncaught TypeError: l.styles.forEach is not a function
    at edit-post.min.js?ver=aec3905d54d344b48f452da0da95d621:7:93641
    at Object.useMemo (react-dom.min.js?ver=17.0.1:220:462)
    at c.useMemo (react.min.js?ver=17.0.1:30:236)
    at zt (edit-post.min.js?ver=aec3905d54d344b48f452da0da95d621:7:93610)
    at Le (react-dom.min.js?ver=17.0.1:100:3)
    at Pj (react-dom.min.js?ver=17.0.1:231:183)
    at di (react-dom.min.js?ver=17.0.1:168:305)
    at Nj (react-dom.min.js?ver=17.0.1:168:236)
    at sc (react-dom.min.js?ver=17.0.1:168:96)
    at gf (react-dom.min.js?ver=17.0.1:162:109)`

I deactivated all the plugins but that didn't solve it. When i switched theme to TwentyTwenty everything is working fine.
Also when i remove this line `add_filter( 'block_editor_settings_all', __NAMESPACE__ . '\remove_gutenberg_inline_styles', 10, 2 );` everything works fine (except the styling of the title area, they changed it a little bit).

**Comment by ronilaukkarinen** [comment]
Just updated. It seems 5.9 is indeed breaking things.

![Screen-Shot-2022-01-26-16-16-11 89](https://user-images.githubusercontent.com/1534150/151179218-75ec20e4-4a6d-4043-a253-82e4de9a9a51.png)

Investigating...
Thanks for the report.

**Comment by ronilaukkarinen** [comment]
@villekujansuu @mlichwa @owsw This bug has been fixed.

WordPress changes the array where styles are outputted and that broke the rendering of the editor. I also added extra check in case if for some reason it changes again in the future. The way to unset styles is currently a bit hacky, feel free to suggest better option.

What you'll need to implement in your themes is to replace the hook:

https://github.com/digitoimistodude/air-light/blob/07307cef3a3d68fde2e3b98b1bf0d4a2910ff47d/inc/hooks/gutenberg.php#L85-L95

...and replace the new title styles for 5.9:

https://github.com/digitoimistodude/air-light/blob/07307cef3a3d68fde2e3b98b1bf0d4a2910ff47d/inc/hooks/gutenberg.php#L108-L174

Thank you everyone for chiming in!

**Comment by ronilaukkarinen** [comment]
For the record, it should look like this in the newest version:

![airdev test_wp_wp-admin_post php_post=701 action=edit (3)](https://user-images.githubusercontent.com/1534150/151187317-5043a347-4b8d-44a9-95e4-98bb2c0edec6.png)

Enjoy!

**Comment by villekujansuu** [comment]
All works well now. 
Thanks for the fast fix :)

**Comment by mlichwa** [comment]
Thank you for taking care of it so fast!
