### ISSUE TITLE
Slick slider in Gutenberg Editor not working

### ISSUE THREAD

**Issue by flegfleg** [digitoimistodude/air-light#147]
Hi, i remember that the ACF slick slider used to work in the editor, now it only shows the slides (with correct css, but below each other). 
Unfortunately i cannot find the Air-Light version where is worked or was able to re-enable it myself. 
Could you give me a hint how to achieve this? 
Thanks!
Flo

**Comment by ronilaukkarinen** [comment]
Hello @flegfleg, you can find the working example [here](https://github.com/digitoimistodude/air-blocks/blob/0c0686c99a64c7474108bb05d0414b67afaa8036/content/themes/air-blocks/js/src/gutenberg-editor.js).

**Comment by flegfleg** [comment]
Oh great thanks!
