### ISSUE TITLE
do air-blocks require the dudestack?

### ISSUE THREAD

**Issue by shaunsantacruz** [digitoimistodude/air-light#150]
Is the dudestack required to use air-blocks? They look great but I'm running air-light on MAMP but can't figure out how to use air-blocks.

**Comment by ronilaukkarinen** [comment]
Yes, check out the prequisities [here](https://github.com/digitoimistodude/air-blocks#prequisities). Please open an issue to [air-blocks issue tracker](https://github.com/digitoimistodude/air-blocks/issues) if you have any more questions.
