### ISSUE TITLE
Columns are not responsive

### ISSUE THREAD

**Issue by shaunsantacruz** [digitoimistodude/air-light#151]
The columns on smaller screens are not stacking resulting in unreadable content.

e.g. https://airwptheme.com/demo/blog/

**Comment by ronilaukkarinen** [comment]
Thanks for opening an issue. I double checked and this is actually not a bug. We are using deprecated text blocks in the demo. They should be regular columns where there's "Stack on mobile" setting nowadays. 

![Screen-Shot-2022-05-12-10-40-26 79](https://user-images.githubusercontent.com/1534150/168018094-c8b48798-8493-4815-8929-70235fba1a7e.png)

I'll fix the demo asap.

**Comment by ronilaukkarinen** [comment]
@shaunsantacruz New version is out! Revamped the demo content so blocks are now on their separate views. Here's [columns](https://airwptheme.com/demo/columns/).
