### ISSUE TITLE
is there a different way to create custom blocks in this theme?

### ISSUE THREAD

**Issue by Zhoha28** [digitoimistodude/air-light#156]
I have used [this](https://github.com/digitoimistodude/air-light/wiki/Using-with-Local-by-Flywheel-or-other-3rd-party-development-environment) method to install the theme.
Can someone please help me understand why I am facing an issue with air blocks ([using this documentation to add a new block](https://docs.airwptheme.com/air-blocks/how-to-create-a-new-reusable-block-for-air-blocks-and-importer-script)).

ERROR - 
```
Checking if we have supported version of the theme... 
cat: /var/www/blank_starter/content/themes/starter-themewithoutvue/functions.php: No such file or directory

The version of your theme 'starter-themewithoutvue' is . Air-blocks require at least 8.4.2. Sorry. The newtheme script will now quit...
```

**Comment by ronilaukkarinen** [comment]
Hello @Zhoha28 and thanks for the issue. You are using the wrong documentation for blocks. That one is how to add block to the import script, not on how to create blocks. We should have clarified that and for that I'm sorry. I have edited the doc to prevent more confusion.

Our documentation is a bit incomplete at the moment regarding to the blocks and building themes. Please use this documentation to build your own blocks: [Creating your own Gutenberg blocks with Air light and Advanced Custom Fields](https://github.com/digitoimistodude/air-light/wiki/Creating-your-own-Gutenberg-blocks-with-Air-light-and-Advanced-Custom-Fields).

Have fun!

**Comment by Zhoha28** [comment]
Question, so pardon me if I am understanding things a bit wrong here ( still trying to understand how everything is tied together), 
1. the way we add blocks is using ACF, not air-blocks? if so then what is the difference between the two?
2. is there also documentation for adding modern frameworks into it, like Vue or react for that matter?

Thanks again for the help !

**Comment by ronilaukkarinen** [comment]
1. [Air-blocks](https://github.com/digitoimistodude/air-blocks) is a collection of ACF Gutenberg blocks. ACF (Advanced Custom Fields) is a plugin for creating fields and blocks.

2. There is no documentation as we don't provide support or help building websites. Air-light is a developer starter theme which you can use as a "blank slate" or "base" to build whatever you want, exactly like [_s](https://github.com/Automattic/_s) or [sage](https://github.com/roots/sage) to name a few.

Air-light supports Vanilla JS/ES6 by default, you can start building your js modules to src/js/moduels and adding inits to [front-end.js](https://github.com/digitoimistodude/air-light/blob/e6ac0a020ae2e83b6c26564929bfdd4d6c4bf1ca/js/src/front-end.js). With vue.js you need to install couple of npm packages like [vue](https://github.com/vuejs/vue), [vue-loader](https://vue-loader.vuejs.org/) for webpack in root level of your project and [axios](https://github.com/axios/axios) in the theme. Then you'd need to config your webpack for vue.js... we've done this couple of times with our client themes based on Air-light. However, this kind of documentation would be out of scope of Air-light as we only provide the base theme and nothing else. If you'd like to contribute to the documentation on how to build more with Air-light, feel free to send a PR!
