### ISSUE TITLE
How do I use the hamburger menu on my PC? 

### ISSUE THREAD

**Issue by meno010** [digitoimistodude/air-light#160]
How do I change the default menu on my PC version devices to the hamburger menu?

**Comment by ronilaukkarinen** [comment]
I'm not sure I understand what the question is. Can you please elaborate? What are you going to achieve, what file you are modifying and what's the problem? Use screenshots if possible.

You can modify the code freely. We do not offer help in web development so if your question is related to coding websites, you'll have to use Google for that. Closing this issue as for now, please reply if you think it's related to Air-light base code or a bug.
