### ISSUE TITLE
Change env to development

### ISSUE THREAD

**Issue by Zhoha28** [digitoimistodude/air-light#163]
Is there documentation on changing the env to development?

**Comment by timiwahalahti** [comment]
I assume you mean for determining which CSS and JS files to enqueue(?)

Enqueues in [inc/hooks/scripts-styles.php](https://github.com/digitoimistodude/air-light/blob/master/inc/hooks/scripts-styles.php) do use our internal `get_asset_file` function, which takes use of WP core's `wp_get_environment_type` function. That function uses `WP_ENVIRONMENT_TYPE` PHP environment variable or constant.

So the simplest way to change the env is by setting this code to your wp-config.php file:

```php
define(  'WP_ENVIRONMENT_TYPE', 'development'  );
```

Just remember to change it when going to production :) Or make use of `.env` files from which the value for the environment constant is set.

More about the `wp_get_environment_type` function: https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/

I am closing this issue, as it's more of a question than an issue that should be kept open.
