### ISSUE TITLE
Investigate `pll_translatable` not working properly on taxonomies

### ISSUE THREAD

**Issue by timiwahalahti** [digitoimistodude/air-light#186]
@Tumppex and @EliasKau reported that there might be issues with `pll_translatable` on taxonomies. It seems that the settings add the terms to be translated, but for some reason, slugs / URLs might not work as expected.

**Comment by raikasdev** [comment]
This is happening due to Polylang showing the taxonomy or custom post type as enabled, but it doesn't save that to the database, and thy will not generate the paths.
