### ISSUE TITLE
Any plans on implementing theme.json?

### ISSUE THREAD

**Issue by simonwimell** [digitoimistodude/air-light#187]
As the title says; Are there any plans on implementing theme.json for theme settings?

**Comment by ronilaukkarinen** [comment]
No. As we use ACF + Gutenberg (php based) we find no use with html based blocks or a block theme structure. If you have ideas, PRs and feature requests welcome. For now I'm going to close this issue.

**Comment by simonwimell** [comment]
It seems like a lot of theme and gutenberg settings are moving in to theme.json, like color palette and stuff?

**Comment by ronilaukkarinen** [comment]
Yeah, but we are using [ACF blocks](https://www.advancedcustomfields.com/blog/acf-5-8-introducing-acf-blocks-for-gutenberg/) instead of native Gutenberg.

Any suggestions welcome.
