### ISSUE TITLE
 Deprecated: Using ${var} in WordPress 6.4.2

### ISSUE THREAD

**Issue by slopesweb** [digitoimistodude/air-light#209]
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in G:\xampp\htdocs\grandinho\wp-content\themes\air-light-master\inc\hooks\scripts-styles.php on line 109

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in G:\xampp\htdocs\grandinho\wp-content\themes\air-light-master\inc\hooks\scripts-styles.php on line 109

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in G:\xampp\htdocs\grandinho\wp-content\themes\air-light-master\inc\hooks\scripts-styles.php on line 109

**Comment by ronilaukkarinen** [comment]
Thanks for the issue.

- What air-light version are you using?
- What PHP version are you using?

**Comment by ronilaukkarinen** [comment]
Air-light didn't have PHP 8 support in January. This is fixed in 9.4.0.
