### ISSUE TITLE
How to enable sticky-nav functionality

### ISSUE THREAD

**Issue by semidivine** [digitoimistodude/air-light#213]
In the README.md it says Air has a sticky navigation baked in. I downloaded your theme from wordpress.org.

_Adding sticky-nav.js to your gulpfile (already included with [Devpackages](https://github.com/digitoimistodude/devpackages)_
I did not find the script in the current Devpackages.

_Uncommeting sticky-nav import in global.scss_
There is no commented line in global.scss.

Please let me know how to proceed with enabling sticky-nav. Thanks!

**Comment by ronilaukkarinen** [comment]
Outdated information in the README.md. I have now clarified this. Thanks for noticing.
