### ISSUE TITLE
Video on how to install and develop blocks

### ISSUE THREAD

**Issue by vitalijalbu** [digitoimistodude/air-light#225]
Hi guys, I would ask if there's any video or tutorial on how to create beautiful websites using your theme and blocks builder.

**Comment by ronilaukkarinen** [comment]
No, there is none. We don't provide any support for this theme, as it's a developer theme and meant to be hacked to pieces by anyone and can be freely used for anything. [The wiki](https://github.com/digitoimistodude/air-light/wiki) has some content, but not very extensive. Good luck!
