### ISSUE TITLE
Custom ACF Blocks not available on pages

### ISSUE THREAD

**Issue by villekujansuu** [digitoimistodude/air-light#226]
In this version custom ACF Blocks are not available on pages unless the line 140 is changed to `page' => 'acf',` in functions.php. If that line is removed, pages have all core blocks and all ACF blocks.

This becomes an issue if there is a need to have both custom ACF Blocks and some selected core blocks on page.

**Comment by ronilaukkarinen** [comment]
Thanks for informing. I agree, this needs to be improved further. No release is not yet made for this, it's only in the dev-version. In retrospective should'be left that in its own branch.

We'll improve it asap.

**Comment by villekujansuu** [comment]
The version I'm using is actually 9.4.4. Edited the title with right version.

**Comment by villekujansuu** [comment]
> The version I'm using is actually 9.4.4. Don't know where I got version number 9.5 :D  Edited the title with right version.

**Comment by ronilaukkarinen** [comment]
Technically there is no version where this change is present, yet. But the latest main shows the latest version.

https://github.com/digitoimistodude/air-light/blob/b05b3980e85a454b1f0297c4d90c6d78ce652145/CHANGELOG.md?plain=1#L1-L4

**Comment by villekujansuu** [comment]
I see. I accidentally downloaded wrong package. Shouldn't work tired late at night. Thanks for the quick reply.

**Comment by ronilaukkarinen** [comment]
Fixed in the latest main/dev (9.5.0rc). Will be established in the upcoming 9.5.0. Thanks again for the notion @villekujansuu!
