### ISSUE TITLE
How to create a production build for hosting with Air theme?

### ISSUE THREAD

**Issue by just-dismas** [digitoimistodude/air-light#227]
Could you please guide me on how to create a production-ready build of the Air theme to upload to my hosting? Previously, I used the Underscores Starter Theme and wanted to give your theme a try. I set up the theme using Dudestack and Laragon for local development.

Thanks in advance for your help!

**Comment by ronilaukkarinen** [comment]
We don't provide support for creating your own themes, but the README, [wiki](https://github.com/digitoimistodude/air-light/wiki) and [docs](https://docs.airwptheme.com/) (although a bit incomplete) should give you some hints. You can also use the theme without dudestack or any of the other setups we use and like just like in _s you just need to replace all occurrences of air-light to get started.

**Comment by just-dismas** [comment]
Hi,

Thank you for your response!

I think there was a bit of misunderstanding. I’m not looking to create a new theme or make modifications for theme development. I’m simply trying to build a website using the Air-light theme as the foundation. I liked the structure and minimalism of Air-light, and I want to use it for my personal or business site.

I’ve gone through the documentation several times but couldn’t find specific instructions on how to create a full production-ready build for deployment, apart from the parts that mention compiling JS and CSS via Gulp. I’ve set up the theme locally using Laragon and Dudestack, and now I’m looking for some guidance on how to properly prepare the theme for hosting after customization.

I’m not modifying the theme itself, just looking to deploy my customized site built on Air-light.

Thanks again for your help!

**Comment by just-dismas** [comment]
Hi,

Thank you for your response!

I think there was a bit of misunderstanding. I’m not looking to create a new theme or make modifications for theme development. I’m simply trying to build a website using the Air-light theme as the foundation. I liked the structure and minimalism of Air-light, and I want to use it for my personal site.

I’ve gone through the documentation several times but couldn’t find specific instructions on how to create a full production-ready build for deployment, apart from the parts that mention compiling JS and CSS via Gulp. I’ve set up the theme locally using Laragon and Dudestack, and now I’m looking for some guidance on how to properly prepare the theme for hosting after customization.

I’m not modifying the theme itself, just looking to deploy my customized site built on Air-light.

Thanks again for your help!
