### ISSUE TITLE
Keyboard support on mobile navigation

### ISSUE THREAD

**Issue by michaelbourne** [digitoimistodude/air-light#27]
Sorry if this already came across your desk, i could have sworn I opened an issue here but I don't see it, perhaps it was an email. Or I'm losing my mind.

Anyways.

If you shrink your browser window to trigger the mobile navigation mode, and then start to tab through the document, the nav items in the mobile menu as in the tab order. If you open the mobile menu, and then close it, your tab context is still trapped in the mobile menu, so you can't navigate the rest of the document. I've tested this on a clean install with the latest commit.

I was able to fix this on my end with a few changes. The first being to reassign the event listeners on the menu from anonymous functions to declared functions, and then removing those event listeners on menu close. And second by changing the menu CSS to change the visibility to hidden and pointer events to none when closed.

It obviously changes the slide down behavior of the menu, but so far the solution on my end seems to be working fine. I'm happy to send a PR with my changes, but I thought I'd mention it first in case you had your own ideas on fixing it.

**Comment by ronilaukkarinen** [comment]
Huge thanks for investigating on this issue, we have obviously missed that while working on other things. I see the issue here clearly now. Pull requests are welcome, but before merging I'd like to test the behaviour. So send us a PR and we'll look into it!

**Comment by michaelbourne** [comment]
Done. I had to pull it out of a pretty customized theme, but my tests seem to work on it. CSS is opinionated as i went from a slide menu to a fade menu, but that was also to enhance removing the nav from the tab order (and I prefer reduced animation in my a11y dev).

**Comment by michaelbourne** [comment]
Hey @ronilaukkarinen 

Curious if you had a chance to test it out and if you were able to find a better way to fix the problem.

Cheers,

**Comment by ronilaukkarinen** [comment]
Works wonders! Been really busy, sorry for not testing earlier. Thanks for the amazing PR and have a nice christmas! :)
