### ISSUE TITLE
Rebuild style structure to support modular structures like Gutenberg blocks

### ISSUE THREAD

**Issue by Niq1982** [digitoimistodude/air-light#29]
I'd like to move the base styles like headings, fonts, buttons and form fields to mixins. That way it would be a lot easier to keep the styles consistent in different kind of modules and blocks and rewrite Gutenberg block styles to match theme styles. 

Example: 
```
body .wp-block-file {
  .wp-block-file__button {
    @include button;
  }
}
```

**Comment by michaelbourne** [comment]
I do this already in all of my builds, although it is a departure from the current Air standard. Is this something you're interested in adopting @ronilaukkarinen ? I could send a PR next week with my tweaks, which largely move most hard coded values into variables and mixins in your help files.

**Comment by ronilaukkarinen** [comment]
@michaelbourne Would be glad to check it out! Please send a PR and we'll see, might as well be close to our future approach.

**Comment by ronilaukkarinen** [comment]
This has been done in [PR #62](https://github.com/digitoimistodude/air-light/pull/62) and further so closing.
