### ISSUE TITLE
error while gulp watch

### ISSUE THREAD

**Issue by jmsilcom** [digitoimistodude/air-light#31]
hi,
I ca'nt use gulp with air-light worrflow (php storm)
I got the error below :
" Undefined rule font-family-no-missing-generic-family-keyword"
every update on npm / scsslint and others (as https://github.com/digitoimistodude/devpackages)
doesn't work.
Any idea ?
thanks in advance

**Comment by ronilaukkarinen** [comment]
This is actually a known issue and not an error but more of a warning, it works but doesn't lint styles properly. Check out [kwown issues on devpackages](https://github.com/digitoimistodude/devpackages#known-issues). Basically you need to install stylelint globally and copy the latest stylelint under gulp-stylefmt/node_modules. It's known dependency problem in `gulp-stylefmt`, there is a pull request and [issue here](https://github.com/morishitter/stylefmt/issues/334#issuecomment-436552167) and [here](https://github.com/morishitter/gulp-stylefmt/issues/10#issuecomment-462769108) and [here](https://github.com/dmnsgn/sublime-stylefmt/issues/26) but the devs have not been responding.

**Comment by ronilaukkarinen** [comment]
Also related issue: [Deprecated stylefmt dependency in gulp-stylefmt](https://github.com/digitoimistodude/air-light/issues/21). Been open from 2018. I really hope devs do something about this as it's not in my hands.

**Comment by jmsilcom** [comment]
Thanks for information... 
Done, but the gulp watch task is interrupted and I have to run it again and again.
and I have this error : "You need to have Ruby and scss-lint gem installed"

**Comment by ronilaukkarinen** [comment]
Yes, ruby is practically needed for everything these days. Are you running it on a Mac? Windows and Linux environments need more pre-installations, Mac comes with ruby etc. natively. scss-lint is dependency of gulp-scss-lint. They are listed under the "recommended" section https://github.com/digitoimistodude/air-light#requirements (devpackages mostly). Make sure [these](https://github.com/digitoimistodude/devpackages#usage) at least are installed.

**Comment by jmsilcom** [comment]
Hi,
I'm on a Mac.
I'll check again my installation...
Thanks

**Comment by jmsilcom** [comment]
Hi agian,

since I tried again and agin, I still can't use gulp watch.
Others ideas for help ?
Thx

**Comment by ronilaukkarinen** [comment]
I need to know more about your setup. Are you using air-light standalone in your own WP installation or are you using [dudestack](https://github.com/digitoimistodude/dudestack)? Or do you want to contribute to air and using it only? Have you run any start scripts like newtheme.sh? Which version of air-light you are running? Are your projects residing in ~/Projects etc.?

**Comment by jmsilcom** [comment]
I am using air-light standalone in my own WP (locale) installation
I don't run any start script.
I use air-light version 4.9.9
My project is under localwheel version 
(thanks for your time)

**Comment by ronilaukkarinen** [comment]
Please send your gulp watch input from start to save and please send your `pwd` command output from where you start the gulp, thanks!

**Comment by jmsilcom** [comment]
hi Roni,
feel to see bellow what you ask for :

`MacBook-Pro-de-Jean:lao-light jms$ pwd
/Users/jms/Local Sites/lagenceoueb/app/public/wp-content/themes/lao-light
MacBook-Pro-de-Jean:lao-light jms$ gulp watch
assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/jms/Local Sites/lagenceoueb/app/public/wp-content/themes/lao-light/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/jms/Local Sites/lagenceoueb/app/public/wp-content/themes/lao-light/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/jms/Local Sites/lagenceoueb/app/public/wp-content/themes/lao-light/gulpfile.js:399:6)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.execute (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:203:12)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:195:5)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:165:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:110:14
MacBook-Pro-de-Jean:lao-light jms$ 
`
Thanks again

**Comment by ronilaukkarinen** [comment]
It sounds like you have gulp 4 installed. It has different syntax we have not yet implemented. As you can see, we use 3.9.1 in both [air-light](https://github.com/digitoimistodude/air-light/blob/master/package.json#L15) and [devpackages](https://github.com/digitoimistodude/devpackages/blob/master/package.json#L15). So please check that you use the correct gulp version first.

**Comment by jmsilcom** [comment]
MacBook-Pro-de-Jean:lao-light jms$ gulp -v
[09:59:08] CLI version 3.9.1
[09:59:08] Local version 4.0.2
MacBook-Pro-de-Jean:lao-light jms$

**Comment by ronilaukkarinen** [comment]
How about package.json under project or theme? I also noticed you are running gulp inside theme directory, we only do air local development like that and otherwise run gulp under root. But i'm not sure about your local stack, so maybe better you try to figure this out yourself.
