### ISSUE TITLE
Trying to add WP default taxonomy to custom post type

### ISSUE THREAD

**Issue by filipchrapek** [digitoimistodude/air-light#38]
I'm really sorry if that's a general WP question and not air-light specific one - I'll promise not to overuse your support. 

I managed to create a custom post type, but when I try to enable the WP default category taxonomy by updating the `$args` to `'taxonomies' => ['category'],`it doesn't really work.

Can you please advice me how to add default category option to custom post type?

**Comment by Niq1982** [comment]
Hi Filip,

It's seems there is a problem when enabling any taxonomies to post type. I'll have to investigate it further.

**Comment by kiwwwipl** [comment]
Hi Niku,

no rush/pressure, but do you have plans working on this issue? Or it's not sth that will be solved in the near future?

**Comment by Niq1982** [comment]
We have found what causes this. It can be fixed by changing

`// Run theme setup
theme_setup();`

to

`// Run theme setup
add_action( 'init', __NAMESPACE__ . '\theme_setup' );`

in functions.php

Thanks for noticing and opening this issue. :)
