### ISSUE TITLE
Typo in Gutenberg blocks

### ISSUE THREAD

**Issue by iraudasoja** [digitoimistodude/air-light#41]
Typo in Gutenberg allowed blocks -list

Should be `'core/buttons'`

https://github.com/digitoimistodude/air-light/blob/fd1779b91e40c2dbe8e406bf1e0e2aff8faccd30/functions.php#L99

Buttons are disabled by now due to this typo.

**Comment by ronilaukkarinen** [comment]
Good catch, thanks! (you could easily have opened a PR for this)
