### ISSUE TITLE
PHPCS disable or ignore

### ISSUE THREAD

**Issue by Tanmccuin** [digitoimistodude/air-light#50]
Gulp is crashing out for me whenever it can't validate via PHPCS, and or some reason no matter what i do i can't get PHPCS to install globally for VSCODE or otherwise - so at this point i'm looking for an option to just disable PHPCS altogether since i'm not concerned about it in the first place. Thanks guys!

`
[15:50:32] Starting 'phpcs'...
[Browsersync] Reloading Browsers... (buffered 2 events)
[15:50:32] 'phpcs' errored after 393 ms
[15:50:32] Error in plugin "gulp-phpcs"
Message:
    Cannot find "/usr/local/bin/phpcs"
Details:
    domainEmitter: [object Object]
    domainThrown: false

[15:50:32] 'watch' errored after 17 s
`

**Comment by ronilaukkarinen** [comment]
The error should not matter, it just won't lint PHP, saving file works and reloading browser works but it shouldn't be any problem. Of course if you want to suppress the error you should do something about it.

If you want to use phpcs prefereably you need to install it to your ~/Projects folder along with [WordPress-Coding-Standards](https://github.com/WordPress/WordPress-Coding-Standards) [as instructed](https://github.com/digitoimistodude/devpackages#usage), then link to /usr/local/bin/phpcs with command `sudo ln -s /path/to/phpcs /usr/local/bin/phpcs && sudo chmod +x /usr/local/bin/phpcs` and then it should work.

To disable phpcs completely from gulp tasks, just comment the lines in [gulpfile.js](https://github.com/digitoimistodude/air-light/blob/30676aff7fc6530d8231f0c9560aa4c63197488a/gulpfile.js#L3) and [watch task](https://github.com/digitoimistodude/air-light/blob/30676aff7fc6530d8231f0c9560aa4c63197488a/gulp/tasks/watch.js#L16). If you still want browser to reload when editing php files, you may need to edit something else.
