### ISSUE TITLE
use_classic_editor not allowing null without error

### ISSUE THREAD

**Issue by Tanmccuin** [digitoimistodude/air-light#58]
Recently pulled the latest and started setting things up and noted by default that 'page' was set in the use_classic_editor function. Upon removing it, i noted an error flash whenever loading a page in the backend.

https://www.dropbox.com/s/4tkn08lkbutsrbh/Screen%20Shot%202020-12-10%20at%2010.23.49%20PM.png?dl=0

  // If you want to use classic editor somewhere, define it here
  'use_classic_editor' => [ 'page' ],

is there a recommended way to disable this without re-writing much of the gutenberg sub-functions?

**Comment by Niq1982** [comment]
I can't see the whole error message, but did you comment the line or use an empty array? Because you should do the latter, like this: `use_classic_editor => [],`

**Comment by ronilaukkarinen** [comment]
Probably an user error so closing this issue as stale. Please reopen if the issue persists!
