### ISSUE TITLE
Blockquote flowing out of viewport

### ISSUE THREAD

**Issue by casparhubinger** [digitoimistodude/air-light#66]
I noticed on the demo site that the content of the `<blockquote>` element is flowing out of the viewport on smaller screens. Apparently it inherits `width: 100%` from `.gutenberg-content > *`, but it has a left margin of 2rem.

<img width="1680" alt="screenshot-20210220-195944" src="https://user-images.githubusercontent.com/59838989/108605979-af2b6c00-73b7-11eb-8ac6-7a302b81875e.png">

Setting `width: auto` on `.gutenberg-content > blockquote` seems to fix the issue (right padding might need additional adjusting though). 

<img width="1680" alt="screenshot-20210220-200001" src="https://user-images.githubusercontent.com/59838989/108605985-b6527a00-73b7-11eb-82df-1c3680394146.png">

Screenshots taken in Firefox 85.0.1 on macOS Big Sur 11.2.

Sorry, got no setup ready to send a PR these days, but I hope the note is valuable. Great job with the theme!

**Comment by ronilaukkarinen** [comment]
Thank you @casparhubinger. A style bug has been slipped there, we'll fix this soon! 👍  width: auto and calc widths are both equally good options here, we'll check out which is the best considering different scenarios.
