### ISSUE TITLE
Undefined index: extension

### ISSUE THREAD

**Issue by ronilaukkarinen** [digitoimistodude/air-light#70]
Just noticed something breaks after [last refactor](https://github.com/digitoimistodude/air-light/commit/375464d56fcf5937b771b086c3681428466b2c4a).

![Screen-Shot-2021-02-22-15-59-51 83](https://user-images.githubusercontent.com/1534150/108718474-216e8e80-7527-11eb-8fb4-2f9ba61ac04d.png)

**Comment by timiwahalahti** [comment]
Fixed in https://github.com/digitoimistodude/air-light/commit/b4834d858d3edea15a2ac4fdee09bc0a096dd841.
