### ISSUE TITLE
New js module not compiling to js/dist

### ISSUE THREAD

**Issue by kiwwwipl** [digitoimistodude/air-light#74]
I've just notice that not all of the files form js/src (or maybe none) are compiling to js/dist. Do you know what might be the issue?

**Comment by Niq1982** [comment]
Are you using the newest version? We recently changed the JS build to build both production and development versions, which are now built to `js/dev/` and `js/prod/` directories, same also goes with CSS files too. We also introduced a new `get_asset_file()` function, which loads the right ones depending on your current environment.

**Comment by ronilaukkarinen** [comment]
@kiwwwipl Can you elaborate more about the problem? Please provide your Air-light version and possibly gulp js task output.

Just tested the latest version out and cannot reproduce this.

1. Created new module to `js/src/modules/test-module.js`
2. Content:

``` js
document.addEventListener('DOMContentLoaded', () => {
  document.getElementsByTagName('body')[0].style.border = '20px solid #0ff';
});
```

3. Added to ` js/src/front-end.js`:

``` js
import './modules/test-module';
```

4. Tested saving front-end.js and test-module.js separately. With both savings getting gulp output:

```
[13:04:43] Version: webpack 4.44.2
Built at: 02/26/2021 1:04:43 PM
       Asset      Size  Chunks             Chunk Names
    block.js  1.02 KiB       0  [emitted]  block
front-end.js  26.1 KiB       1  [emitted]  front-end
   legacy.js   181 KiB       2  [emitted]  legacy
Entrypoint block = block.js
Entrypoint front-end = front-end.js
Entrypoint legacy = legacy.js
```

`git status` showing changed files:

```
demon air-light (master) s
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   js/dev/front-end.js
	modified:   js/prod/front-end.js
	modified:   js/prod/legacy.js
	modified:   js/src/front-end.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	js/src/modules/test-module.js

no changes added to commit (use "git add" and/or "git commit -a")
```

Should be working fine on latest version (6.8.7).

**Comment by kiwwwipl** [comment]
Pardon, I didn't fully updated the theme, my bad.
