### ISSUE TITLE
ACF not working in frontpage

### ISSUE THREAD

**Issue by ramvyr** [digitoimistodude/air-light#76]
I use acf block in gutenberg with method acf_register_block
In admin page all workin but in front page the_content return empty block with content acf
I check wordpress method the_content

```
function the_content( $more_link_text = null, $strip_teaser = false ) {
	$content = get_the_content( $more_link_text, $strip_teaser );

//ACF data exist

	$content = apply_filters( 'the_content', $content );

// ACF data don't exist

	$content = str_replace( ']]>', ']]&gt;', $content );
	echo $content;
}
```

The problem exists only in your theme

**Comment by ronilaukkarinen** [comment]
It seems you are not using namespaced PHP in your example. Please refer to [documentation](https://github.com/digitoimistodude/air-light#namespaced-php).

**Comment by ramvyr** [comment]
Okay. Thanks anwer.

I added

```
add_action('acf/init',  __NAMESPACE__ . '\register_blocks');

function register_blocks() {
  if (function_exists('acf_register_block')) {
    acf_register_block(array(
      'name' => 'sliders',
      'title' => __('Slider'),
      'description' => __(''),
      'render_template' => get_template_directory() . 'template-parts/_blocks/slider.php',
           'category' => 'common',
      'mode' => 'edit',
      'icon' => 'admin-users'
    ));
 }
}
```

But in front page ACF data not appeared

**Comment by ronilaukkarinen** [comment]
Are you sure that function exists? This is not really a theme related issue, you should ask for help on [ACF forums](https://support.advancedcustomfields.com/forums/).

**Comment by ramvyr** [comment]
Function exist in plugin and I use this code in another theme and all working

add_action('acf/init',   'register_blocks');

function register_blocks() {
  if (function_exists('acf_register_block')) {
    acf_register_block(array(
      'name' => 'sliders',
      'title' => __('Slider'),
      'description' => __(''),
      'render_template' => get_template_directory() . 'template-parts/_blocks/slider.php',
           'category' => 'common',
      'mode' => 'edit',
      'icon' => 'admin-users'
    ));
 }
}

**Comment by ronilaukkarinen** [comment]
That's weird, because in my understanding the latest ACF version does not have `acf_register_block` function, its `acf_register_block_type`.

Have you invoked the namespace before declaring the hook like on our templates [here](https://github.com/digitoimistodude/air-light/blob/a12fa01422ce5862eeec46b3a535665dc2fe6a3c/page.php#L17) for instance? I don't see the full source code here so it's impossible for me to say what's wrong. Do you have any errors or warnings? What does your xdebug or var_dump say? 

We init stuff like this in inc/hooks.php (NB! This is just an example based on one of our projects and may not work in your case, but see it as reference:

``` php
/**
 * ACF blocks
 */
require get_theme_file_path( 'inc/hooks/acf-blocks.php' );
add_action( 'acf/init', __NAMESPACE__ . '\init_acf_block_types' );
```

And inc/hooks/acf-blocks.php:

``` php
<?php
/**
 * @Author: Timi Wahalahti
 * @Date:   2020-09-11 11:43:05
 * @Last Modified by:   Timi Wahalahti
 * @Last Modified time: 2021-03-18 19:08:49
 * @package yourtheme
 */

namespace Air_Light;

function init_acf_block_types() {
  if ( ! function_exists( 'acf_register_block_type' ) ) {
    return;
  }

  acf_register_block_type( [
    'name'              => 'styled-quote',
    'title'             => 'Styled quote',
    'description'       => 'Styled quote description here.',
    'render_callback'   => __NAMESPACE__ . '\render_acf_block',
    'category'          => 'layout',
    'icon'              => 'admin-comments',
    'keywords'          => [ 'quote' ],
    'mode'              => 'edit',
    'supports'          => [
      'align' => false,
    ],
  ] );

  // More block types here...
}

function render_acf_block( $block, $content = '', $is_preview = false, $post_id = 0 ) {
  $show_in_phase = isset( $block['data']['show_in_phase'] ) ? $block['data']['show_in_phase'] : null;
  if ( ! content_can_be_shown( $show_in_phase ) ) {
    return;
  }

  $block_slug = str_replace( 'acf/', '', $block['name'] );
  include get_theme_file_path( "template-parts/blocks/{$block_slug}.php" );
}
````

**Comment by ramvyr** [comment]
Thank you.

`'render_callback'   => __NAMESPACE__ . '\render_acf_block',`
and
```
function render_acf_block( $block ) {
  $block_slug = str_replace( 'acf/', '', $block['name'] );
  include get_theme_file_path( "template-parts/blocks/{$block_slug}.php" );
}
```

Solved my problem
