### ISSUE TITLE
CSS Source Maps

### ISSUE THREAD

**Issue by flegfleg** [digitoimistodude/air-light#79]
Hi, css source maps do not seem to be created. 
How can i enable them? 
Thanks!

**Comment by ronilaukkarinen** [comment]
We currently don't use CSS source maps at all as they have been pretty unreliable in the past. We prefer using DevTools and unminified dev css file, it's pretty easy to find the correct file anyway with modern tools like VSCode. If you or someone has suggestion how to implement them propery to our gulp4 setup all suggestions or pull requests are welcome.

**Comment by flegfleg** [comment]
Hi, thanks for the quick answer. 
If anybody is interested, i implemented source maps here: https://github.com/flegfleg/air-light/commit/c6d87621b1f1ef2962ca57f6f5d0d766ae486da3

**Comment by ronilaukkarinen** [comment]
Nice! Can you send a Pull Request so we can test it out and merge in the repo if it works fine for us?

**Comment by ronilaukkarinen** [comment]
@flegfleg Tried to implement them but these changes seems to have no effect. If you'd like to have them in official repository, please send a PR, thanks!
