### ISSUE TITLE
Add aria-attributes to nav-walker

### ISSUE THREAD

**Issue by LukaszJaro** [digitoimistodude/air-light#93]
### nav-walker.php
For accessibility purposes:
`$atts['aria-current'] = $item->current ? 'page' : '';`

For security:
```
 //$atts['rel']    = ! empty( $item->xfn ) ? $item->xfn : '';
      if ( '_blank' === $item->target && empty( $item->xfn ) ) {
				$atts['rel'] = 'noopener noreferrer';
			} else {
				$atts['rel'] = $item->xfn;
			}
```

### Gutenberg
**Missing blocks**
```
      'core/button', //need this to add buttons inline
      'core/group',
      'core/media-text',
      'core/block',
      'core/template',
```
      
**Deprecated blocks**  
```
//'core/subhead', https://developer.wordpress.org/block-editor/how-to-guides/backward-compatibility/deprecations/#3-9-0
//'core/textColumns', https://developer.wordpress.org/block-editor/how-to-guides/backward-compatibility/deprecations/#3-5-0
```

Lastly, missing styles for alignwide and alignfull https://www.billerickson.net/full-and-wide-alignment-in-gutenberg/

**Comment by ronilaukkarinen** [comment]
While you at code level you might as well send a PR for us to review?

**Comment by ronilaukkarinen** [comment]
Quick notes: alignwide and alignfull were there last I checked 🤔 

As for the allowed_blocks. We don't want to allow them all on purpose in the starter. People who build their themes based on Air can just choose which blocks to add. The deprecated blocks need to be removed naturally soon enough.

Aria-current is excellent catch. I've often added that myself but for some reason didn't add it to the theme yet. It seems it have been added to the [original component that menu is based](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/c856e941c4209581f8b90a31cc33350c758b3cfb/class-wp-bootstrap-navwalker.php#L235) as well. We should maybe look on the updates it has been having over the years.

**Comment by ronilaukkarinen** [comment]
Just tested out and everything working from 7.0.3 to 7.1.7. Are you sure you are running the new enough version? There has been various Gutenberg fixes from 7.0.3 like [this here](https://github.com/digitoimistodude/air-light/pull/82).

The latest is 7.1.7 released 6 minutes ago. 🙂 

I'm going to rename this issue considering the nav-walker as it's the only one yet to be done.

**Comment by ronilaukkarinen** [comment]
Just tested a bit the [original nav walker](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/master/class-wp-bootstrap-navwalker.php) our nav is based on, it contains aria-labelledby and other features we could implement the same time we do this aria-current update.

PRs still accepted.

**Comment by LukaszJaro** [comment]
Thanks @ronilaukkarinen been very busy but will have a look when I get some time!
