### ISSUE TITLE
Should we replace namespace Air_Light; in replaces script

### ISSUE THREAD

**Issue by ronilaukkarinen** [digitoimistodude/air-light#96]
I've been asked many times why [Air_Light namespace](https://github.com/digitoimistodude/air-light/blob/80fc10c3a246d307ea795c3e576d141e556eca35/functions.php#L15) is not being replaced. Should we add it to [replaces](https://github.com/digitoimistodude/air-light/blob/80fc10c3a246d307ea795c3e576d141e556eca35/bin/tasks/replaces.sh).

Why not:
- No special need for it
- It's a "fingerprint" of Air_Light theme
- It's unique and not accidentally the same than other namespaces possible used, if any

Why replace:
- To be consistent with other replaces like textdomain, screenreadertext-functions, etc.
- Starter theme mentality - starter stuff should not be visible after creating a new theme
- Why not replace it? No big reasons why not?
- Anything else?

**Comment by michaelbourne** [comment]
I've left it intact on all my projects. Replacing it is trivial though. Start theme mentality would be the only real argument I guess, but leaving copyrights in place as per GPL seems to make that moot. There will always be a reference to the original works.

**Comment by ronilaukkarinen** [comment]
@michaelbourne Thank you for the input. I agree, it's hard to say whether to do this or not, it's equally acceptable in both ways. Some of our users _may_ see this as a confusing factor since everything else air-related gets replaced. Let's give this a bit more thought though... The father of this idea @Niq1982 said in our private Slack channel something similar, that there is no obvious reasons why the namespace should not be replaced, however if replaceable theme name is in fact something very generic it may cause conflicts. So Air_Light namespace is really a safe bet.

**Comment by Niq1982** [comment]
If namespace gets replaced, user should be able to define the namespace in the start script separately, `Air_Light` being the default. I think at least it's a bad idea to try to generate a valid namespace from the theme slug. There's always the issue that less PHP-oriented people don't yet understand namespaces. So if we have a prompt for setting the namespace, it should explain this shortly and recommend to keep it as is if the user don't know namespaces as it's always a valid choice to keep it as `Air_Light`.

**Comment by ronilaukkarinen** [comment]
Excellent points. However maybe extra query in the script is too much... I for one don't like the idea of having to either type or skip the query every time running the script.

**Comment by timiwahalahti** [comment]
Agree with @michaelbourne and @ronilaukkarinen here. If one wants to change the namespace afterwards, it's trivial to do with search & replace even after the project has been started.

I'm going to close this ticket, as the general consensus seems to be that changing the namespace isn't necessary. Let's re-open if new views in this matter raises.
