### ISSUE TITLE
404 for gutenberg.css

### ISSUE THREAD

**Issue by thomasparkes** [digitoimistodude/air-light#99]
Hi, 

My editor is delivering a 404 for the following, there is no guternberg.css in the directory.

![Screen Shot 2021-05-08 at 10 20 29 am](https://user-images.githubusercontent.com/46695948/117519590-86df0100-afe7-11eb-8a15-a6778c3389f0.png)

```
/Users/thomasparkes/Downloads/air-light-master 3/inc/hooks/gutenberg.php:
   82  
   83    // Enqueue editor styles.
   84:   add_editor_style( get_theme_file_uri( get_asset_file( 'gutenberg.css' ) ) );
   85  }
   86  
```

**Comment by ronilaukkarinen** [comment]
Hello! Thanks for reporting this issue. We are in between of some upcoming Gutenber updates and lately notice this as well. Please in the meantime rename the file [here](https://github.com/digitoimistodude/air-light/blob/0b46072f35c1b6170eaa956d9da64b6af2036194/inc/hooks/gutenberg.php#L84).
